### ISSUE TITLE
I agree it isn't exactly the same, and I just thought of another reason it is kind of challenging: the sim is multi-threaded. This works ok with the larger system heap, but doesn't really make sense to use a smaller heap when multiple threads are using it.

### ISSUE THREAD

**Issue by ghost** [mcu-tools/trusted-firmware-m#1]
I agree it isn't exactly the same, and I just thought of another reason it is kind of challenging: the sim is multi-threaded. This works ok with the larger system heap, but doesn't really make sense to use a smaller heap when multiple threads are using it.

I don't think it is really a zephyr-specific thing, although the configs are Zephyr specific (I'm not quite sure how the configuration is evening happening with the other platforms).

I'll put this as a someday thing, since it is kind of quite a bit of work for something that would be revealed pretty quickly on target.

_Originally posted by @d3zd3z in https://github.com/mcu-tools/mcuboot/issues/1203#issuecomment-965761879_

**Comment by d3zd3z** [comment]
Did you intend to create a new issue under tfm? This seems like kind of a long title for an issue.
